services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./BE/src/.env
    volumes:
      - ./BE/src:/app
    # You could remove depends_on if you want to start them independently in CI;
    # but for local dev, it’s often convenient to keep it.
    depends_on:
      db:
        condition: service_healthy
    # 로컬 테스트를 위한 네트워크 설정
    networks:
      - Aira_shared_local_network

  db:
    image: mysql:8.0
    restart: always
    env_file: 
      - ./BE/src/.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    # 로컬 테스트를 위한 네트워크 설정
    networks:
      - Aira_shared_local_network

volumes:
  db_data:

# 로컬 테스트를 위한 네트워크 정의, 터미널에서 미리 docker network create Aira_shared_local_network 명령 실행해야 함
networks:
  Aira_shared_local_network:
    external : true